routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('locale/{locale}', function ($locale) {
    \Illuminate\Support\Facades\Session::put('locale', $locale);
    return redirect()->back();
})->name('locale');

Route::get('/', function () {
    return view('welcome');
});



//Route::get('lang/{lang}', ['as' => 'site.changeLanguage', 'uses' => 'HomeController@changeLanguage']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::prefix('tag')->name('tag.')->group(function () {
    Route::get('index', 'TagController@index')->name('index');
    Route::get('edit/{id}', 'TagController@edit')->name('edit');
    Route::get('create', 'TagController@create')->name('create');
    Route::get('delete/{id}', 'TagController@delete')->name('delete');
    Route::post('save/{id?}', 'TagController@save')->name('save');
});

Route::prefix('product')->name('product.')->group(function () {
    Route::get('index', 'ProductController@index')->name('index');
    Route::get('edit/{id}', 'ProductController@edit')->name('edit');
    Route::get('create', 'ProductController@create')->name('create');
    Route::get('delete/{id}', 'ProductController@delete')->name('delete');
    Route::post('save/{id?}', 'ProductController@save')->name('save');
});

Route::prefix('product/document')->name('document.')->group(function () {
    Route::get('download/{id}', 'ProductDocumentController@download')->name('download');
    Route::get('delete/{id}', 'ProductDocumentController@delete')->name('delete');
});


Route::post('tags/search', 'ProductTagController@postSearchTag')->name('tags.search.select2');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use \Astrotomic\Translatable\Translatable;

    protected $table = 'products';
    protected $dates = ['created_at', 'updated_at'];

    public $translatedAttributes = ['name', 'description', 'price'];

    protected $fillable = [
        'status',
        'publish_start',
        'publish_end'
    ];

    public function getStatus(){
        return trans(StaticTypes::$status_types[$this->status]);
    }

    public function getStatusForTable(){
        return '<span class="badge badge-' . StaticTypes::$status_types_badges[$this->status] . '">' . trans(StaticTypes::$status_types[$this->status]) . '</span>';
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\ProductDocuments;
use App\ProductTags;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Str;
use Kris\LaravelFormBuilder\FormBuilder;

class ProductController extends HomeController
{
    public function __construct(){
        parent::__construct();
    }

    public function index(){
        $elements = Product::orderBy('id');

        return view('product.index', ['elements' => $elements]);
    }
    public function create(FormBuilder $formBuilder){
        //$element = new Conference();

        $form = $formBuilder->create('App\Forms\ProductForm', [
            'method' => 'POST',
            //'model' => $element,
            'url' => route('product.save'),
            'files' => true
        ]);

        return view("product.form", [
            'form' => $form,
            'documents' => null,
            'tags' => null
        ]);
    }

    public function edit($id, FormBuilder $formBuilder){
        $element = Product::where(['id' => $id])->first();

        $documents = ProductDocuments::where('product_id', $element->id)->get();

        $tags = ProductTags::where('product_id', $element->id)->get();

        $element->publish_start = Carbon::create($element->publish_start)->format('Y-m-d\TH:i:s');
        $element->publish_end = Carbon::create($element->publish_end)->format('Y-m-d\TH:i:s');


        $form = $formBuilder->create('App\Forms\ProductForm', [
            'method' => 'POST',
            'model' => $element,
            'url' => route('product.save', ["id" => $id]),
            'files' => true
        ]);

        //dd($element);

        return view("product.form", [
            'form' => $form,
            'documents' =>  $documents,
            'tags' => $tags
        ]);
    }

    public function delete($id){
        $element = Product::where('id', $id)->first();
        $element->status = 0;
        if($element->save()) {
            return redirect()->back()->with('success', 'Product deleted successful!');
        }
        else{
            return redirect()->back()->with('error', 'Product deletion error!');
        }
    }

    public function save($id = null, Request $request, FormBuilder $formBuilder){
        $element = Product::where('id', $id)->first();

        if(!$element){
            $element = new Product();
        }

        $form = $formBuilder->create('App\Forms\ProductForm', [
            'method' => 'POST',
            'model' => $element,
            'url' => route('product.save', ["id" => $id]),
            'files' => true
        ]);

        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        $data = $form->validate()->getData();


        $element->status = $request->get('status');
        $element->publish_start = Carbon::createFromFormat('Y-m-d\TH:i:s', $request->get('publish_start'));
        $element->publish_end = Carbon::createFromFormat('Y-m-d\TH:i:s', $request->get('publish_end'));
        foreach( Config::get('app.languages') as $key => $lang ) {
            $element->translateOrNew($key)->name = $data['translate_' . $key . '_name'];
            $element->translateOrNew($key)->description = $data['translate_' . $key . '_description'];
            $element->translateOrNew($key)->price = $data['translate_' . $key . '_price'];
        }

        //dd($request->all());

        if($element->save()) {


            if(!is_null($request->get('tag_collection'))){
                $tag_ids = explode(';', $request->get('tag_collection'));

                for($i = 0; $i < count($tag_ids); $i++){
                    if(ProductTags::createTag($tag_ids[$i], $form->getModel()->id)['status'] == 'error'){
                        return redirect()->back()->with('error', 'Error during saving a product tag!');
                    }
                }
            }


            foreach($form->getFields() as $field) {


                if (Str::contains($field->getName(), 'document')) {
                    $file = $form->getRequest()->file($field->getName());
                    if (!is_null($file)) {
                        //$doc_type = Str::replaceLast('_document', '', $field->getName());
                        if(ProductDocuments::createDocument($file, $form->getModel()->id)['status'] == 'error'){
                            return redirect()->back()->with('error', 'Error during saving a product document!');
                        }
                    }
                }
            }

            return redirect()->route('product.index')->with('success', 'Product saved successful!');
        }
        else {
            return redirect()->back()->with('error', 'Error during saving the product!');
        }
    }
}

resources/views/product/form.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="animated fadeIn">


            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#product" role="tab" aria-controls="product">{{ trans('site.models.product') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#tags" role="tab" aria-controls="tags">{{ trans('site.actions.assigned_tags') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#documents" role="tab" aria-controls="documents">{{ trans('site.actions.related_documents') }}</a>
                </li>

            </ul>

            <div class="tab-content">

                <div class="tab-pane active" id="product" role="tabpanel">
                    <div class="card">
                        <div class="card-header">
                            {{ trans('site.models.product') }}
                        </div>
                        <div class="card-body">
                            {!! form($form) !!}
                        </div>
                    </div>

                </div>




                <div class="tab-pane" id="tags" role="tabpanel">

                    @if(!is_null($tags))
                        <div class="card">
                            <div class="card-header">
                                {{ trans('site.actions.assigned_tags') }}
                            </div>
                            <div class="card-body">
                                @if($tags->count())
                                    <table class="table table-responsive-sm table-striped">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>{{ trans('site.table.name') }}</th>
                                            <th>{{ trans('site.table.status') }}</th>
                                            <th>{{ trans('site.table.created_at') }}</th>
                                            <th>{{ trans('site.table.actions') }}</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($tags as $tag)
                                            @include('product.partials.tags-table-row')
                                        @endforeach
                                        </tbody>
                                    </table>
                                @else
                                    <h6>{{ trans('site.actions.no_tag_found') }}.</h6>
                                @endif
                            </div>
                        </div>
                    @endif

                </div>




                <div class="tab-pane" id="documents" role="tabpanel">
                    @if(!is_null($documents))
                        <div class="card">
                            <div class="card-header">
                                {{ trans('site.actions.related_documents') }}
                            </div>
                            <div class="card-body">
                                @if($documents->count())
                                    <table class="table table-responsive-sm table-striped">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>{{ trans('site.table.path') }}</th>
                                            <th>{{ trans('site.table.status') }}</th>
                                            <th>{{ trans('site.table.created_at') }}</th>
                                            <th>{{ trans('site.table.actions') }}</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($documents as $document)
                                            @include('product.partials.documents-table-row')
                                        @endforeach
                                        </tbody>
                                    </table>
                                @else
                                    <h6>{{ trans('site.actions.no_document_found') }}.</h6>
                                @endif
                            </div>
                        </div>
                    @endif
                </div>








            </div>

        </div>
    </div>


@endsection

resources/views/product/index.blade.php
@extends('layouts.app')


@section('content')

    @include('components.messages')

    <div class="container">
        <div class="animated fadeIn">

            <div class="card">
                <div class="card-header">
                    {{ trans('site.models.product') }}
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <a href="{{ route('home') }}" class="btn btn-info"><i class="fa fa-plus"></i>
                            {{ trans('site.actions.back') }}</a>

                        <a href="{{ route('product.create') }}" class="btn btn-info"><i class="fa fa-plus"></i>
                            {{ trans('site.actions.create_new_product') }}</a>
                    </div>

                    @if($elements->count())
                        <table class="table table-responsive-sm table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>{{ trans('site.table.name') }}</th>
                                <th>{{ trans('site.table.status') }}</th>
                                <th>{{ trans('site.table.price') }}</th>
                                <th>{{ trans('site.table.publish_start') }}</th>
                                <th>{{ trans('site.table.publish_end') }}</th>
                                <th>{{ trans('site.table.created_at') }}</th>
                                <th>{{ trans('site.table.actions') }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($elements->get() as $element)
                                @include('product.partials.products-table-row')
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <h6>{{ trans('site.actions.no_product_found') }}.</h6>
                    @endif
                </div>
            </div>

        </div>
    </div>


@endsection