routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('locale/{locale}', function ($locale) {
    \Illuminate\Support\Facades\Session::put('locale', $locale);
    return redirect()->back();
})->name('locale');

Route::get('/', function () {
    return view('welcome');
});



//Route::get('lang/{lang}', ['as' => 'site.changeLanguage', 'uses' => 'HomeController@changeLanguage']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::prefix('tag')->name('tag.')->group(function () {
    Route::get('index', 'TagController@index')->name('index');
    Route::get('edit/{id}', 'TagController@edit')->name('edit');
    Route::get('create', 'TagController@create')->name('create');
    Route::get('delete/{id}', 'TagController@delete')->name('delete');
    Route::post('save/{id?}', 'TagController@save')->name('save');
});

Route::prefix('product')->name('product.')->group(function () {
    Route::get('index', 'ProductController@index')->name('index');
    Route::get('edit/{id}', 'ProductController@edit')->name('edit');
    Route::get('create', 'ProductController@create')->name('create');
    Route::get('delete/{id}', 'ProductController@delete')->name('delete');
    Route::post('save/{id?}', 'ProductController@save')->name('save');
});

Route::prefix('product/document')->name('document.')->group(function () {
    Route::get('download/{id}', 'ProductDocumentController@download')->name('download');
    Route::get('delete/{id}', 'ProductDocumentController@delete')->name('delete');
});


Route::post('tags/search', 'ProductTagController@postSearchTag')->name('tags.search.select2');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use \Astrotomic\Translatable\Translatable;

    protected $table = 'tags';
    protected $dates = ['created_at', 'updated_at'];



    public $translatedAttributes = ['name'];

    protected $fillable = [
        'status'
    ];

    public function getStatus(){
        return trans(StaticTypes::$status_types[$this->status]);
    }

    public function getStatusForTable(){
        return '<span class="badge badge-' . StaticTypes::$status_types_badges[$this->status] . '">' . trans(StaticTypes::$status_types[$this->status]) . '</span>';
    }

}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\ProductTags;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Config;
use Kris\LaravelFormBuilder\FormBuilder;

class TagController extends HomeController
{
    public function __construct(){
        parent::__construct();
    }

    public function index(){
        $elements = Tag::orderBy('id');

        //dd($elements->first()->translate('en')->name);

        return view('tag.index', ['elements' => $elements]);
    }


    public function create(FormBuilder $formBuilder){

        $form = $formBuilder->create('App\Forms\TagForm', [
            'method' => 'POST',
            //'model' => $element,
            'url' => route('tag.save'),
            'files' => true
        ]);

        return view("tag.form", [ 'form' => $form, 'products' => null ]);
    }

    public function edit($id, FormBuilder $formBuilder){
        $element = Tag::where('id', $id)->first();

        $managed = ProductTags::where('tag_id', $element->id)->get();

        $form = $formBuilder->create('App\Forms\TagForm', [
            'method' => 'POST',
            'model' => $element,
            'url' => route('tag.save', ["id" => $id]),
            'files' => true
        ]);

        return view("tag.form", [ 'form' => $form, 'products' => $managed ]);
    }

    public function delete($id){
        $element = Tag::where('id', $id)->first();
        $element->status = 0;
        if($element->save()) {
            return redirect()->back()->with('success', 'Tag inactivate successful!');
        }
        else{
            return redirect()->back()->with('error', 'Tag inactivation error!');
        }
    }

    public function save($id = null, Request $request, FormBuilder $formBuilder){
        $tag = Tag::where('id', $id)->first();

        if(!$tag){
            $tag = new Tag();
        }

        $form = $formBuilder->create('App\Forms\TagForm', [
            'method' => 'POST',
            'model' => $tag,
            'url' => route('tag.save', ["id" => $id]),
            'files' => true
        ]);

        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        $data = $form->validate()->getData();


        $tag->status = $request->get('status');
        foreach( Config::get('app.languages') as $key => $lang ) {
            $tag->translateOrNew($key)->name = $data['translate_' . $key . '_name'];
        }





        if($tag->save()) {
            foreach($form->getFields() as $field) {
                if($field->getName() == 'product_collection' && !is_null($field->getRawValue())){
                    $product_ids = explode(';', $field->getRawValue());

                    for($i = 0; $i < count($product_ids); $i++){
                        if(ProductTags::createTag($form->getModel()->id, Product::where('id', $product_ids[$i])->first())['status'] == 'error'){
                            return redirect()->back()->with('error', 'Error during saving a product tag!');
                        }
                    }
                }
            }
            return redirect()->route('tag.index')->with('success', 'Tag saved successful!');
        }
        else{
            return redirect()->back()->with('error', 'Error during saving the tag!');
        }
    }
}

resources/views/tag/form.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="animated fadeIn">

            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#tag" role="tab" aria-controls="tag">{{ trans('site.models.tag') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#products" role="tab" aria-controls="products">{{ trans('site.models.product') }}</a>
                </li>
            </ul>

            <div class="tab-content">

                <div class="tab-pane active" id="tag" role="tabpanel">

                    <div class="card">
                        <div class="card-header">
                            {{ trans('site.models.tag') }}
                        </div>
                        <div class="card-body">
                            {!! form($form) !!}
                        </div>
                    </div>


                </div>
                <div class="tab-pane" id="products" role="tabpanel">

                    @if(!is_null($products))
                        <div class="card">
                            <div class="card-header">
                                {{ trans('site.actions.connected_products') }}
                            </div>
                            <div class="card-body">
                                @if($products->count())
                                    <table class="table table-responsive-sm table-striped">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Status</th>
                                            <th>Publish start</th>
                                            <th>Publish end</th>
                                            <th>Created at</th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($products as $product)
                                            @include('tag.partials.products-table-row')
                                        @endforeach
                                        </tbody>
                                    </table>
                                @else
                                    <h6>{{ trans('site.actions.no_connected_products') }}</h6>
                                @endif
                            </div>
                        </div>
                    @endif

                </div>

            </div>
        </div>


@endsection

resources/views/tag/index.blade.php
@extends('layouts.app')


@section('content')

    @include('components.messages')

    <div class="container">
        <div class="animated fadeIn">

            <div class="card">
                <div class="card-header">
                    {{ trans('site.models.tag') }}
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <a href="{{ route('home') }}" class="btn btn-info"><i class="fa fa-plus"></i>
                            {{ trans('site.actions.back') }}</a>

                        <a href="{{ route('tag.create') }}" class="btn btn-info"><i class="fa fa-plus"></i>
                            {{ trans('site.actions.create_new_tag') }}</a>
                    </div>

                    @if($elements->count())
                        <table class="table table-responsive-sm table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>{{ trans('site.table.name') }}</th>
                                <th>{{ trans('site.table.status') }}</th>
                                <th>{{ trans('site.table.created_at') }}</th>
                                <th>{{ trans('site.table.actions') }}</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($elements->get() as $element)

                                @include('tag.partials.tags-table-row')
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <h6>{{ trans('site.actions.no_tag_found') }}.</h6>
                    @endif
                </div>
            </div>

        </div>
    </div>


@endsection